# Generated by Django 5.1.6 on 2026-03-08 13:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_image_upload_to, verbose_name='Изображение'),
        ),
    ]
