FROM redis:7.4-alpine
WORKDIR /usr/local/etc/redis

COPY ./conf/redis/redis.conf .
COPY ./conf/redis/users.acl .

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf", "--aclfile", "/usr/local/etc/redis/users.acl" ]
