# Generated by Django 5.1.6 on 2025-02-21 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.IntegerField(choices=[(3, 'Завершённый'), (2, 'Начатый'), (1, 'Отложенный'), (0, 'Добавленный')], default=0, verbose_name='Состояние')),
                ('rank', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Оценка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.product', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентари',
                'db_table': 'inventory',
            },
        ),
    ]
