# Generated by Django 5.1.6 on 2025-06-20 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_author'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.IntegerField(choices=[(3, 'Начато'), (2, 'Отложено'), (1, 'Добавлено'), (0, 'Завершено')], db_index=True, default=1, verbose_name='Состояние'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'user')},
        ),
    ]
