# Generated by Django 5.1.6 on 2025-10-03 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='rank',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
