# Generated by Django 5.1.6 on 2025-08-05 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
    ]
