# Generated by Django 5.1.6 on 2025-09-19 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='rank',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
