# Generated by Django 5.1.6 on 2025-10-03 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
