# Generated by Django 5.1.6 on 2026-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='review',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Отзыв'),
        ),
    ]
