# Generated by Django 5.1.6 on 2025-06-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.author'),
        ),
    ]
