# Generated by Django 5.1.6 on 2026-03-08 13:37

import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=goods.models.product_image_upload_to, verbose_name='Изображение'),
        ),
    ]
