# Generated by Django 5.1.6 on 2025-02-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_author_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='product_tag', to='goods.tag', verbose_name='Теги'),
        ),
    ]
